### ISSUE TITLE
Issue with the dataset on zenodo

### ISSUE THREAD

**Issue by ayush-raj7** [jakelever/corona-ml#1]
Very nice repo.
On zenodo it is mentioned that the following fields are present:
pubmed_id: PubMed identifier (optional)
pmcid: PubMed Central identifier (optional)
doi: Digital object identifier (optional)
cord_uid: CORD-19 identifier (optional)
url: URL
journal: Journal/preprint server
publish_year: Year of publication (optional)
publish_month: Month of publication (optional)
publish_day: Day of publication (optional)
title: Title of article
abstract: Abstract of article (optional)
is_preprint: Whether the article is a preprint
categories: Predicted categories for article
entities: Extracted entities (e.g. drugs) with identifiers and locations within text

But when I download the data
The following fields are there

['abstract', 'annotations', 'articletypes', 'arxiv_id', 'authors', 'chemicals', 'cord_uid', 'doi', 'entities', 'ids_from_merged_documents', 'inferred_article_type', 'is_preprint', 'journal', 'journaliso', 'languages', 'license', 'mag_id', 'medline_pubtype', 'mesh', 'pdf_json_files', 'pmc_json_files', 'pmcid', 'publish_day', 'publish_month', 'publish_year', 'pubmed_id', 'reference_count', 's2_id', 'sha', 'source_x', 'supplementary_concepts', 'title', 'topics', 'url', 'urls', 'viruses', 'who_covidence_id']

Also, can you explain what is articletypes and topics?

**Comment by jakelever** [comment]
Hey, thanks for raising this. I hadn't realised this document had got a little out-of-date. I will add some clean up so that the fields properly batch the description in the document.

In the mean time, the articletypes and topics contain the predicted article types (e.g. Research, Review, Comment/Editorial) and the topics contain things like Therapeutics & Long Haul. Previously they were combined in the categories field but this was replaced with the two separate fields. I'll update the README to match

**Comment by ayush-raj7** [comment]
Thanks for the response. 
So, you are saying in articletypes, the predicted category is there. I want to run an evaluation on the dataset using the model. How can I get the ground truth category?
In the annotated_documents.json.gz file there is abstract, title and annotations. Is annotations, the ground truth category?
And why there are multiple values in each annotation? I am assuming those values are articletypes.

**Comment by jakelever** [comment]
The ground truth is in the annotated_documents.json.gz file. The Zenodo data contains the final predictions merged in with ground truth for all documents, so you don't want that. 

The annotations field in the annotated_documents.json.gz is the ground truth category (which contains article types and topic). It's a multilabel problem so each document can be tagged with multiple topics & article types.

**Comment by ayush-raj7** [comment]
Thanks a lot for the response!!
